server:
  port: 3000

spring:
  application:
    name: gateway-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server


eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.50.7.8:3150/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: full
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-service/v3/api-docs
        name: USER API
      - url: /notification-service/v3/api-docs
        name: NOTIFICATION API
      - url: /promotion-service/v3/api-docs
        name: PROMOTION API
      - url: /point-service/v3/api-docs
        name: POINT API
      - url: /chat-service/v3/api-docs
        name: CHAT API


logging:
  level:
    org.nextme.gatewayserver.config: INFO
